module.exports = [
  "READ_FILE",
  "WRITE_FILE",
  "SELECT_DIRECTORY",
  "SAVE_USER_DATA",
  "USER_DATA",
  "GENERATOR_LIST",
  "ADD_GENERATOR",
  "UPDATE_GENERATOR",
  "DELETE_GENERATOR",
  "GET_GENERATOR",
  "GENERATE_STRUCTURE_GENERATOR",
];
